/// flutter_web icons Myflutter_webApp
/// Copyright (C) 2019 by original authors @ flutter_webicon.com, fontello.com
/// This font was generated by flutter_webIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter_web:
///   fonts:
///    - family:  Myflutter_webApp
///      fonts:
///       - asset: fonts/Myflutter_webApp.ttf
///
/// 
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
///
import 'package:flutter_web/widgets.dart';

class Myflutter_webApp {
  Myflutter_webApp._();

  static const _kFontFam = 'Myflutter_webApp';

  static const IconData water = const IconData(0xe800, fontFamily: _kFontFam);
}
