name: dial_in_web
description: An app built using Flutter for web

environment:
  # You must be using Flutter >=1.5.0 or Dart >=2.3.0
  sdk: '>=2.3.0-dev.0.1 <3.0.0'

dependencies:
  flutter_web: any
  flutter_web_ui: any

  firebase_core: ^0.3.0+1
  cloud_firestore: ^0.9.7
  firebase_auth: ^0.8.2
  firebase_storage: ^2.1.0+1

  flutter_slidable: "^0.4.9"
  datetime_picker_formfield: ^0.1.8
  path_provider: ^0.5.0+1
  image: ^2.0.7  
  flutter_rating: ^0.0.2
  rxdart: ^0.21.0
  scoped_model: ^1.0.1
  shimmer: ^1.0.0
  screen: ^0.0.5
  
  image_picker: ^0.5.2
  path: ^1.6.2
  pull_to_refresh: ^1.1.6 
  cached_network_image: ^0.7.0
  package_info: ^0.4.0+2
  sentry: ^2.2.0
  flutter_launcher_icons: "^0.7.0"
  fancy_bottom_navigation: ^0.3.2
  bubble_tab_indicator: "^0.1.4"
  shared_preferences: ^0.5.1+2
  material_design_icons_flutter: 3.2.3595
  font_awesome_flutter: ^8.4.0
  diacritic: ^0.1.1
  mailer: ^2.2.1
  flutter_cache_manager: ^0.3.2
  flutter_sticky_header: "^0.3.4"

dev_dependencies:
  build_runner: ^1.4.0
  build_web_compilers: ^2.0.0
  pedantic: ^1.0.0

dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter_web/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter_web/flutter_web
      path: packages/flutter_web_ui
