/// flutter_web icons Myflutter_webApp
/// Copyright (C) 2018 by original authors @ flutter_webicon.com, fontello.com
/// This font was generated by flutter_webIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter_web:
///   fonts:
///    - family:  Myflutter_webApp
///      fonts:
///       - asset: fonts/Myflutter_webApp.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
/// * Meteocons, Copyright (C) 2012 by Alessio Atzeni
///         Author:    Alessio Atzeni
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.alessioatzeni.com
/// * Linecons, Copyright (C) 2013 by Designmodo
///         Author:    Designmodo for Smashing Magazine
///         License:   CC BY ()
///         Homepage:  http://designmodo.com/linecons-free/
/// * Maki, Copyright (C) Mapbox, LCC
///         Author:    Mapbox
///         License:   BSD (https://github.com/mapbox/maki/blob/gh-pages/LICENSE.txt)
///         Homepage:  http://mapbox.com/maki/
/// * Linearicons Free, Copyright (C) Linearicons.com
///         Author:    Perxis
///         License:   CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/)
///         Homepage:  https://linearicons.com
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
// import 'package:flutter_web/widgets.dart';

// class Myflutter_webApp {
//   Myflutter_webApp._();

//   static const _kFontFam = 'Myflutter_webApp';

//   static const IconData crop_original = const IconData(0xe800, fontFamily: _kFontFam);
//   static const IconData landscape = const IconData(0xe801, fontFamily: _kFontFam);
//   static const IconData local_florist = const IconData(0xe802, fontFamily: _kFontFam);
//   static const IconData nature_people = const IconData(0xe803, fontFamily: _kFontFam);
//   static const IconData nature = const IconData(0xe804, fontFamily: _kFontFam);
//   static const IconData network_check = const IconData(0xe805, fontFamily: _kFontFam);
//   static const IconData photo_size_select_actual = const IconData(0xe806, fontFamily: _kFontFam);
//   static const IconData photo_library = const IconData(0xe807, fontFamily: _kFontFam);
//   static const IconData 001_folder = const IconData(0xe808, fontFamily: _kFontFam);
//   static const IconData 002_analysis = const IconData(0xe809, fontFamily: _kFontFam);
//   static const IconData 003_stopwatch = const IconData(0xe80a, fontFamily: _kFontFam);
//   static const IconData 004_flag = const IconData(0xe80b, fontFamily: _kFontFam);
//   static const IconData 006_star = const IconData(0xe80c, fontFamily: _kFontFam);
//   static const IconData 008_calendar = const IconData(0xe80d, fontFamily: _kFontFam);
//   static const IconData 005_favorite = const IconData(0xe80e, fontFamily: _kFontFam);
//   static const IconData 007_barista = const IconData(0xe80f, fontFamily: _kFontFam);
//   static const IconData 009_heat = const IconData(0xe810, fontFamily: _kFontFam);
//   static const IconData 010_cog = const IconData(0xe811, fontFamily: _kFontFam);
//   static const IconData photo_size_select_large = const IconData(0xe812, fontFamily: _kFontFam);
//   static const IconData 013_grinder = const IconData(0xe813, fontFamily: _kFontFam);
//   static const IconData 014_filter = const IconData(0xe814, fontFamily: _kFontFam);
//   static const IconData photo = const IconData(0xe815, fontFamily: _kFontFam);
//   static const IconData menu = const IconData(0xe816, fontFamily: _kFontFam);
//   static const IconData pin_drop = const IconData(0xe817, fontFamily: _kFontFam);
//   static const IconData place = const IconData(0xe818, fontFamily: _kFontFam);
//   static const IconData public = const IconData(0xe819, fontFamily: _kFontFam);
//   static const IconData portrait = const IconData(0xe81a, fontFamily: _kFontFam);
//   static const IconData heart_empty = const IconData(0xe81b, fontFamily: _kFontFam);
//   static const IconData heart = const IconData(0xe81c, fontFamily: _kFontFam);
//   static const IconData mail = const IconData(0xe81d, fontFamily: _kFontFam);
//   static const IconData info = const IconData(0xe81e, fontFamily: _kFontFam);
//   static const IconData feather = const IconData(0xe81f, fontFamily: _kFontFam);
//   static const IconData flag = const IconData(0xe820, fontFamily: _kFontFam);
//   static const IconData flag_filled = const IconData(0xe821, fontFamily: _kFontFam);
//   static const IconData home = const IconData(0xe822, fontFamily: _kFontFam);
//   static const IconData thumbs_up = const IconData(0xe823, fontFamily: _kFontFam);
//   static const IconData edit = const IconData(0xe824, fontFamily: _kFontFam);
//   static const IconData flask = const IconData(0xe825, fontFamily: _kFontFam);
//   static const IconData coffee = const IconData(0xe826, fontFamily: _kFontFam);
//   static const IconData chart_alt_outline = const IconData(0xe827, fontFamily: _kFontFam);
//   static const IconData windy_rain_inv = const IconData(0xe828, fontFamily: _kFontFam);
//   static const IconData snow_heavy_inv = const IconData(0xe829, fontFamily: _kFontFam);
//   static const IconData cloud_sun = const IconData(0xe82a, fontFamily: _kFontFam);
//   static const IconData globe = const IconData(0xe82b, fontFamily: _kFontFam);
//   static const IconData tree_2 = const IconData(0xe83f, fontFamily: _kFontFam);
//   static const IconData earth = const IconData(0xe853, fontFamily: _kFontFam);
//   static const IconData tree = const IconData(0xf1bb, fontFamily: _kFontFam);
// }
